In [5]:
import numpy as np
import pandas as pd

In [2]:
lista_1 = (1, 2, 3)
lista_2 = (1, 2, 3)
lista_1 == lista_2

True

In [3]:
'ç' == 'Ç'

False

In [8]:
array = np.random.normal(0, 1, 1_000).reshape (10, -1)
array.shape

(10, 100)

In [10]:
array = np.random.normal(0, 1, 1_000).reshape (10, -1)
array[:2]

array([[ 0.25255566, -0.4980901 , -0.10982173, -0.1943676 ,  0.75388759,
         0.40356034, -0.8458581 , -0.49416841,  0.00933953, -0.46337356,
         0.53810738,  1.04984354, -1.20159437, -0.20258928,  0.0639223 ,
         0.6250205 ,  0.43986642, -1.49295365,  0.81554683, -0.93722462,
        -2.07701415, -0.04895861,  2.15722363, -0.37976659, -0.43484939,
        -1.02333761, -0.75313121, -1.36580037, -1.23060164, -0.9499147 ,
         2.86184278, -0.02023077, -0.2316662 , -1.06936475,  1.13229908,
         0.04901609, -0.43569545, -1.66131843, -0.42033988,  1.05175752,
        -0.21622225, -0.52297326,  1.39277488,  0.05756779,  0.48431431,
        -0.69627108, -0.65141028,  0.20019748, -0.98909988,  0.72367586,
        -0.84382527, -0.10795286,  0.24879733,  2.32495747,  0.43972398,
         0.01400887, -0.19147475,  0.40046875,  1.03832338,  1.74091576,
         1.59660087,  0.26866011, -1.91044276,  0.76786428,  0.34969766,
        -1.70785542, -0.38056191, -0.3850884 ,  1.00044364, -1.1372184 ,
         0.09094843,  0.34643859,  0.39221412,  1.99061123,  0.2458388 ,
         2.38074686,  0.44895015,  1.27900657, -0.98409723, -0.6137143 ,
         1.16575782,  0.16394541, -1.65909469,  0.91041169,  0.5523261 ,
        -0.11956957,  0.99913735,  2.47168358, -1.15014691, -0.62208968,
         0.11082171,  1.68892802, -0.39140082,  0.20882855,  0.89541356,
        -1.26029849, -0.56505121, -0.33796221,  0.16281183, -0.79344348],
       [-2.34918162, -0.02901824, -1.79095197, -0.8238965 ,  0.91668207,
        -1.44678887, -0.27726211, -0.77271453,  0.65742169,  0.51971397,
         1.6113682 ,  0.77484916,  2.3677028 ,  1.4317593 , -0.19209547,
         0.78564468,  0.23606653,  0.42893382,  1.08296255,  1.34337104,
         1.90995463, -1.4889181 ,  0.1525607 ,  1.21495481, -1.52773114,
        -0.34345903,  1.00763341, -1.26788776, -0.118523  ,  1.46583254,
        -1.15981629, -1.02045833, -0.17188919,  0.29478167, -0.05959092,
         0.9355051 ,  0.5472312 , -0.28241641, -0.2425812 ,  0.62506097,
         0.36466162, -0.37874567,  0.23711854,  0.98373832, -0.21470575,
         0.30492395, -1.0793997 , -0.1711608 , -0.17070533,  1.51626362,
         0.69895673,  0.56944851,  0.36771542,  0.65662208,  0.59186198,
         0.65418936,  0.08664324, -1.67590598,  1.15657805,  0.32871104,
        -0.60347501,  1.07588652,  1.84262003,  0.83480581,  0.448851  ,
        -0.7673333 ,  0.85584537, -0.16230332,  0.90450022,  0.72739457,
        -0.06478939,  0.54447639,  1.10866149,  0.19020275,  0.2209419 ,
        -0.88440181, -0.11779267,  0.36215456,  0.81761076, -0.47348783,
        -1.64319925,  0.46891173,  2.12340055,  2.50505368, -0.1119567 ,
         0.98850653,  0.06216811,  0.42689209, -0.64176668, -1.12735013,
         0.07454949, -0.72362729, -0.65835101,  0.19058174,  0.53678274,
        -1.07087257,  0.21947898,  0.47197523, -0.55857669, -0.54730712]])

In [12]:
array = np.random.normal(0, 1, 1_000).reshape (-1, 10)
array[2]

array([-1.08064196,  0.48600732, -0.42770902,  0.98026315,  1.59366879,
       -1.06626147,  0.80453094,  0.42558407,  0.39099958, -0.21712956])

In [18]:
np.random.seed(42)
array_1 = np.random.normal(0, 1, 1_000).reshape (-1, 10)
array_2 = np.random.normal(0, 1, 1_000).reshape (-1, 10)
print(array_1[:1])
print(array_2[:1])

[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
   1.57921282  0.76743473 -0.46947439  0.54256004]]
[[ 1.39935544  0.92463368  0.05963037 -0.64693678  0.69822331  0.39348539
   0.89519322  0.6351718   1.04955272 -0.53523521]]

In [19]:
array_1 == array_2

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [20]:
pd.DataFrame(array_1)

,0,1,2,3,4,5,6,7,8,9
0,0.496714,-0.138264,0.647689,1.523030,-0.234153,-0.234137,1.579213,0.767435,-0.469474,0.542560
1,-0.463418,-0.465730,0.241962,-1.913280,-1.724918,-0.562288,-1.012831,0.314247,-0.908024,-1.412304
2,1.465649,-0.225776,0.067528,-1.424748,-0.544383,0.110923,-1.150994,0.375698,-0.600639,-0.291694
3,-0.601707,1.852278,-0.013497,-1.057711,0.822545,-1.220844,0.208864,-1.959670,-1.328186,0.196861
4,0.738467,0.171368,-0.115648,-0.301104,-1.478522,-0.719844,-0.460639,1.057122,0.343618,-1.763040
...,...,...,...,...,...,...,...,...,...,...
95,-0.241236,0.352055,-1.251539,1.443765,-0.082151,1.117296,0.342725,0.456753,0.569767,0.447709
96,0.642723,1.329153,0.196521,0.709004,-0.089736,1.440117,-0.676392,1.800940,-0.040158,-1.430775
97,0.128104,-0.681052,0.840644,-0.652624,-0.446183,-1.889541,-0.452306,-2.423879,-1.583903,0.760415
98,0.785800,0.425458,-0.966976,-0.047711,-0.003603,-1.158365,1.503398,0.877362,-0.220964,0.026886
99,0.208383,-2.041735,-0.247177,-0.681984,-1.001620,-0.281100,1.797687,0.640843,-0.571179,0.572583

In [21]:
pd.DataFrame(array_1) == pd.DataFrame(array_2)

        0      1      2      3      4      5      6      7      8      9
0   False  False  False  False  False  False  False  False  False  False
1   False  False  False  False  False  False  False  False  False  False
2   False  False  False  False  False  False  False  False  False  False
3   False  False  False  False  False  False  False  False  False  False
4   False  False  False  False  False  False  False  False  False  False
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
95  False  False  False  False  False  False  False  False  False  False
96  False  False  False  False  False  False  False  False  False  False
97  False  False  False  False  False  False  False  False  False  False
98  False  False  False  False  False  False  False  False  False  False
99  False  False  False  False  False  False  False  False  False  False

[100 rows x 10 columns]

In [22]:
pd.DataFrame(array_1) <= pd.DataFrame(array_2)

        0      1      2      3      4      5      6      7      8      9
0    True   True  False  False   True   True  False  False   True  False
1    True   True   True   True   True   True   True  False   True   True
2   False  False  False   True   True   True   True  False   True  False
3    True  False   True   True  False   True  False   True   True   True
4    True  False   True   True   True   True   True  False   True   True
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
95  False   True   True  False  False   True  False   True   True  False
96  False  False   True  False   True  False   True  False  False   True
97   True  False  False   True   True   True   True   True   True  False
98  False  False   True   True   True   True  False  False  False   True
99   True   True   True   True   True   True  False  False   True  False

[100 rows x 10 columns]